cout << "       ," << endl;
cout << "       \\`-._           __" << endl;
cout << "        \\  `-..____,.'  `." << endl;
cout << "         :`.         /    \\`." << endl;
cout << "         :  )       :      : \\" << endl;
cout << "          ;'        '   ;  |  :" << endl;
cout << "          )..      .. .:.`.;  :" << endl;
cout << "         /::...  .:::...   ` ;" << endl;
cout << "         ; _ '    __        /:\\" << endl;
cout << "         `:o>   /\\o_>      ;:. `." << endl;
cout << "        `-`.__ ;   __..--- /:.   \\" << endl;
cout << "        === \\_/   ;=====_.':.     ;" << endl;
cout << "        ,/'`--'...`--....        ;" << endl;
cout << "              ;                    ;" << endl;
cout << "            .'                      ;" << endl;
cout << "          .'                        ;" << endl;
cout << "        .'     ..     ,      .       ;" << endl;
cout << "       :       ::..  /      ;::.     |" << endl;
cout << "      /      `.;::.  |       ;:..    ;" << endl;
cout << "     :         |:.   :       ;:.    ;" << endl;
cout << "     :         ::     ;:..   |.    ;" << endl;
cout << "      :       :;      :::....|     |" << endl;
cout << "      /\\     ,/ \\      ;:::::;     ;" << endl;
cout << "    .:. \\:..|    :     ; '.--|     ;" << endl;
cout << "   ::.  :''  `-.,,;     ;'   ;     ;" << endl;
cout << ".-'. _.'\\      / `;      \\,__:      \\" << endl;
cout << "`---'    `----'   ;      /    \\,.,,,/" << endl;
cout << "                   `----`              " << endl;